-- Source domain tables preserve the selected CDC values before cleaning.
CREATE TABLE demographics (
 SEQN INTEGER PRIMARY KEY, SDDSRVYR INTEGER NOT NULL CHECK(SDDSRVYR=66),
 RIDSTATR INTEGER, RIAGENDR INTEGER, RIDAGEYR REAL, RIDRETH3 INTEGER,
 RIDEXPRG INTEGER, WTMECPRP REAL, SDMVSTRA INTEGER, SDMVPSU INTEGER, INDFMPIR REAL
);
CREATE TABLE liver_exam (
 SEQN INTEGER PRIMARY KEY REFERENCES demographics(SEQN), LUAXSTAT INTEGER,
 LUARXNC INTEGER, LUANMVGP INTEGER, LUANMTGP INTEGER, LUXCAPM REAL,
 LUXCPIQR REAL, LUXSMED REAL, LUXSIQR REAL, LUXSIQRM REAL
);
CREATE TABLE anthropometry (
 SEQN INTEGER PRIMARY KEY REFERENCES demographics(SEQN), BMXBMI REAL
);
CREATE TABLE glycohemoglobin (
 SEQN INTEGER PRIMARY KEY REFERENCES demographics(SEQN), LBXGH REAL
);
CREATE TABLE alcohol (
 SEQN INTEGER PRIMARY KEY REFERENCES demographics(SEQN), ALQ111 INTEGER,
 ALQ121 INTEGER, ALQ130 INTEGER
);
CREATE VIEW source_join AS
 SELECT d.*, l.LUAXSTAT,l.LUARXNC,l.LUXCAPM,l.LUXCPIQR,l.LUXSMED,
 b.BMXBMI,g.LBXGH,a.ALQ111,a.ALQ121,a.ALQ130
 FROM demographics d LEFT JOIN liver_exam l USING(SEQN)
 LEFT JOIN anthropometry b USING(SEQN)
 LEFT JOIN glycohemoglobin g USING(SEQN)
 LEFT JOIN alcohol a USING(SEQN);

